/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author T440s
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaFroma
     */
    public GlavnaForma() {
        initComponents();
    }

    public JButton getBtnClan() {
        return btnClan;
    }

    public void setBtnClan(JButton btnClan) {
        this.btnClan = btnClan;
    }

    public JButton getBtnDrutvenaIgra() {
        return btnDrutvenaIgra;
    }

    public void setBtnDrutvenaIgra(JButton btnDrutvenaIgra) {
        this.btnDrutvenaIgra = btnDrutvenaIgra;
    }

    public JButton getBtnPotvrda() {
        return btnPotvrda;
    }

    public void setBtnPotvrda(JButton btnPotvrda) {
        this.btnPotvrda = btnPotvrda;
    }

    public JLabel getLblUlogovani() {
        return lblUlogovani;
    }

    public void setLblUlogovani(JLabel lblUlogovani) {
        this.lblUlogovani = lblUlogovani;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnClan = new javax.swing.JButton();
        btnDrutvenaIgra = new javax.swing.JButton();
        btnPotvrda = new javax.swing.JButton();
        lblUlogovani = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Glavna forma");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Izaberite akciju!"));

        btnClan.setText("Clan");

        btnDrutvenaIgra.setText("Drustvena igra");

        btnPotvrda.setText("Potvrda o iznajmljivanju");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnClan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnDrutvenaIgra)
                .addGap(54, 54, 54)
                .addComponent(btnPotvrda)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClan)
                    .addComponent(btnDrutvenaIgra)
                    .addComponent(btnPotvrda))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        lblUlogovani.setText("Zdravo, ulgovani!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblUlogovani))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblUlogovani)
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClan;
    private javax.swing.JButton btnDrutvenaIgra;
    private javax.swing.JButton btnPotvrda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblUlogovani;
    // End of variables declaration//GEN-END:variables

    public void dodajOsluskivacClan(ActionListener actionListener) {
        btnClan.addActionListener(actionListener);
    }

    public void dodajOsluskivacIgra(ActionListener actionListener) {
        btnDrutvenaIgra.addActionListener(actionListener);
    }

    public void dodajOsluskivacPotvrda(ActionListener actionListener) {
        btnPotvrda.addActionListener(actionListener);
    }
}
