/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import server.Server;

/**
 *
 * @author T440s
 */
public class ServerskaForma extends javax.swing.JFrame {

    Server serverNit;
    
    public ServerskaForma() {
        initComponents();
        btnUgasi.setEnabled(false);
        serverNit = new Server();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        btnPokreni = new javax.swing.JButton();
        btnUgasi = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuKonfiguracija = new javax.swing.JMenu();
        itemBaza = new javax.swing.JMenuItem();
        itemPort = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Serverska forma");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pokretanje i gasenje servera"));

        jLabel1.setText("Status: ");

        lblStatus.setText("Server je ugasen!");

        btnPokreni.setText("Pokreni");
        btnPokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniActionPerformed(evt);
            }
        });

        btnUgasi.setText("Ugasi");
        btnUgasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUgasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus)
                .addGap(63, 63, 63)
                .addComponent(btnPokreni)
                .addGap(28, 28, 28)
                .addComponent(btnUgasi)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblStatus)
                    .addComponent(btnPokreni)
                    .addComponent(btnUgasi))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        menuKonfiguracija.setText("Konfiguracija");

        itemBaza.setText("Baza");
        itemBaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBazaActionPerformed(evt);
            }
        });
        menuKonfiguracija.add(itemBaza);

        itemPort.setText("Port");
        itemPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPortActionPerformed(evt);
            }
        });
        menuKonfiguracija.add(itemPort);

        jMenuBar1.add(menuKonfiguracija);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemBazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBazaActionPerformed
        new KonfiguracijaBazeForma(this, true).setVisible(true);
                
    }//GEN-LAST:event_itemBazaActionPerformed

    private void itemPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPortActionPerformed
        new KonfiguracijaPortaForma(this, true).setVisible(true);
    }//GEN-LAST:event_itemPortActionPerformed

    private void btnPokreniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniActionPerformed
        serverNit.start();
        btnPokreni.setEnabled(false);
        btnUgasi.setEnabled(true);
        lblStatus.setText("Server je pokrenut!");
    }//GEN-LAST:event_btnPokreniActionPerformed

    private void btnUgasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUgasiActionPerformed
        serverNit.zaustaviServer();
        btnPokreni.setEnabled(true);
        btnUgasi.setEnabled(false);
        lblStatus.setText("Server je ugasen!");
    }//GEN-LAST:event_btnUgasiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPokreni;
    private javax.swing.JButton btnUgasi;
    private javax.swing.JMenuItem itemBaza;
    private javax.swing.JMenuItem itemPort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JMenu menuKonfiguracija;
    // End of variables declaration//GEN-END:variables
}
